Css frameworks
elli95/css-frameworks-ca pull request #1
Opened 2023-08-30 16:33 UTC by elli95

2023-08-31 11:42 UTC, sulenchy commented on index.html
> +                    <input type="text" name="password" id="password" class="form-control" minlength="8"  placeholder="Password" required>
This should be of type `password`

2023-08-31 12:18 UTC, sulenchy requested changes
Have a few comments for you at the top.

2023-08-31 12:18 UTC, sulenchy commented on feed/index.html
> +            <ul class="list-group gap-2">
On a bigger screen, you have the thumbnails stacked up on a column. It would be better if you could utilize the spaces around the thumbnails on a bigger screen. Try this 
```
<ul class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 gap-1">
...
</ul>```

You can also find an example at https://getbootstrap.com/docs/5.3/examples/album/.

2023-08-31 15:33 UTC, elli95 commented on index.html
> +                    <input type="text" name="password" id="password" class="form-control" minlength="8"  placeholder="Password" required>
Thank you!
I will fix this.

2023-08-31 15:38 UTC, elli95 commented on feed/index.html
> +            <ul class="list-group gap-2">
Thanks for the reply, didn't think much of it at the moment.
I will adjust it.

2023-09-01 11:13 UTC, sulenchy approved these changes

2023-09-03 12:50 UTC, merged